#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image
image:
  #- Visual Studio 2013 #disable since Ninja is not available
  - Visual Studio 2019
  - macos
  - Ubuntu

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release
  - Debug

environment:
  XML_CATALOG_FILES: /usr/local/etc/xml/catalog

install:
  - sh: if [ "`uname -s`" = "Darwin" ]; then export XML_CATALOG_FILES=/usr/local/etc/xml/catalog; brew install ninja gtk-doc; else sudo apt-get -y install gtk-doc-tools; fi

build_script:
  - mkdir build
  - cd build
  - cmd: cmake -G Ninja -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DENABLE_GTK_DOC=OFF -DICAL_GLIB=False ..
  - sh: cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
  - cmake --build .
  - cmd: cmake --build . --target install
  - sh: sudo cmake --build . --target install
  - ctest --test-dir .

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
  - provider: Email
    to:
      - winter@kde.org
    on_build_success: false
    on_build_failure: true
